#!/system/bin/sh

# screenstate_scaling, governor and threshold control
# original by 'FloHimself'(florian.schaefer@gmail.com)
# modifications by 'zacharias.maladroit' and 'well.heeled.man'

# Further modifications by Efpophis (billcrossley@gmail.com) and TkGlitch (Ti3noU@gmail.Com)

# as it turns out, I get better battery life without this running
# at all. Maybe the thing polling constantly is draining
# the battery faster than if it was just left alone...

GLITCH_DIR=/system/etc/glitch-config

# if our config directory is not there, create it and populate it with
# reasonable defaults. Otherwise, we'll pay attn to what the user has there
if [ ! -d $GLITCH_DIR ]
then
    # oops! default to off because this means the kernel probably didn't flash right?!?
    SCREENSTATE_SCALING_ACTIVE="inactive"
else

    # set this to "active" to use this stuff
    SCREENSTATE_SCALING_ACTIVE=`cat ${GLITCH_DIR}/screenstate_scaling`
    # use the one configured
    SLEEP_GOVERNOR=`cat ${GLITCH_DIR}/sleep_governor`
fi

# use the one voltage control has specified
# assumes 1. we're awake at start, and 2. that VC has set the governor according to user wishes.
# EDIT: after some testing, it turns out these assumptions are correct, so this works.
AWAKE_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`


(while [ $SCREENSTATE_SCALING_ACTIVE = "active" ]
do
    # the "cat" call blocks on these files if the device is not in the state being checked for
    # meaning execution will wait here until the phone wakes up. Neat.
    AWAKE=`cat /sys/power/wait_for_fb_wake`
    
    if [ $AWAKE = "awake" ]; then
	echo $AWAKE_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

	# DIDLE enabler
	echo 0 > /sys/devices/platform/bt_rfkill/rfkill/rfkill0/soft

AWAKE=
    fi

    # the "cat" call blocks on these files if the device is not in the state being checked for
    # meaning execution will wait here until the phone goes to sleep. Neat.
    SLEEPING=`cat /sys/power/wait_for_fb_sleep`
    
    if [ $SLEEPING = "sleeping" ]; then
    
	# save the current awake gov for restoration later - someone may have changed it
	# we can do this since coming into this if statement is edge-sensitive, i/e: it
	# only happens when the state initially transitions to "sleeping"
	AWAKE_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

        echo $SLEEP_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

	# DIDLE enabler
	echo 1 > /sys/devices/platform/bt_rfkill/rfkill/rfkill0/soft

	# Finishing.

	SLEEPING=
    fi

    SCREENSTATE_SCALING_ACTIVE=`cat ${GLITCH_DIR}/screenstate_scaling`
    
done &)
