#!/system/bin/sh

# screenstate_scaling, governor and threshold control
# original by 'FloHimself'(florian.schaefer@gmail.com)
# modifications by 'zacharias.maladroit' and 'well.heeled.man'

#AWAKE_GOVERNOR="interactive"
#AWAKE_GOVERNOR="smartass"
#AWAKE_GOVERNOR="ondemand"
#AWAKE_GOVERNOR="conservative"
#SLEEP_GOVERNOR="conservative"
#SLEEP_GOVERNOR="powersave"

# =========
# One governor to rule them all
# =========

AWAKE_GOVERNOR="ondemand"
SLEEP_GOVERNOR="conservative"

##
## Only uncomment two sections, one for each screen state.
##

# Polling for AWAKE_GOVERNOR state.

(while [ 1 ]
do
    AWAKE=`cat /sys/power/wait_for_fb_wake`
    if [ $AWAKE = "awake" ]; then
        echo $AWAKE_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		
# =========
# Smartass settings (slightly more battery friendly than Glitch Kernel defaults - peformance penalty unclear)
# =========

#       echo "50" > /sys/devices/system/cpu/cpu0/cpufreq/smartass/max_cpu_load
#       echo "30" > /sys/devices/system/cpu/cpu0/cpufreq/smartass/min_cpu_load
#       echo "800000" > /sys/devices/system/cpu/cpu0/cpufreq/smartass/up_min_freq
#       echo "400000" > /sys/devices/system/cpu/cpu0/cpufreq/smartass/sleep_max_freq

# =========
# Ondemand settings [more aggressive power savings vs. standard ondemand]
# =========

#       echo "98" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold       
#		echo "300000" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate

# =========
# Ondemand settings [experimental] (max frequency at 800 MHz, more aggressive up and down sampling, while staying longer at higher frequencies during load)
# =========

#       echo "100" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
#       echo "200" > /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias
#       echo "100000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
		
# =========
# Conservative settings [SavagedZen governor-like] (conservative AWAKE_GOVERNOR)
# =========

#       echo "75" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
#       echo "30" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
#       echo "50" > /sys/devices/system/cpu/cpufreq/conservative/freq_step
#       echo "80000" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate

# Polling for SLEEP_GOVERNOR state.

	AWAKE=
    fi

    SLEEPING=`cat /sys/power/wait_for_fb_sleep`
    if [ $SLEEPING = "sleeping" ]; then
        echo $SLEEP_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# =========
# Conservative settings [very conservative](conservative SLEEP_GOVERNOR)
# =========

        echo "90" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
        echo "50" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
        echo "10" > /sys/devices/system/cpu/cpufreq/conservative/freq_step
        echo "500000" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate

# Finishing.		
		
	SLEEPING=
    fi    
done &)
